version: '3.7'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000 --settings=flud.settings.asgi
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: